name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: build and push swath
      run: ./scripts/push.sh swath
    - name: build and push pythainlp
      run: ./scripts/push.sh pythainlp
    - name: build and push deepcut
      run: ./scripts/push.sh deepcut
    - name: build and push cutkum
      run: ./scripts/push.sh cutkum
    - name: build and push sertis
      run: ./scripts/push.sh sertis
    - name: build and push tltk
      run: ./scripts/push.sh tltk
    - name: build and push chrome
      run: ./scripts/push.sh chrome
