name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: build
      run: |
        ./scripts/build.sh pythainlp
        ./scripts/build.sh deepcut
        ./scripts/build.sh cutkum
        ./scripts/build.sh sertis
        ./scripts/build.sh tltk
        ./scripts/build.sh swath
        ./scripts/build.sh chrome
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: pythainlp/word-tokenizers
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
